name: squadsplitter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  fluttertoast: ^8.2.2
  flutter_easyloading: ^3.0.5
  #google:
  json_serializable: ^6.1.5
  json_annotation: ^4.8.1
  lottie: ^2.6.0

  dio: ^5.2.1
  flutter_expandable_fab: ^2.0.0

  #hive:
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  mazarbul: ^1.1.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/lottie_json/
